services:
  backend:
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    ports:
      - "5026:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - app-network
  
  web:
    build:
      context: ./Web/
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - backend

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users_info
    ports:
      - "5444:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6400:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

networks:
  app-network:

volumes:
  postgres-data: