services:
  api:
    build:
      context: .
      dockerfile: TicTacToe.API/Dockerfile
    ports:
      - "5026:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=personal_info;Username=postgres;Password=1234
      - REDIS_HOST=redis
    networks:
      - app-network
  
  frontend:
    build:
      context: ../TicTacToe/TicTacToe.View/Web/
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - api

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: personal_info
    ports:
      - "5444:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6400:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

networks:
  app-network:

volumes:
  postgres-data: